#!/usr/bin/env python3
"""
Build registry/assets/*.json - the catalogue the mod manager's Texture packs
tab browses.

The companion site at https://bentrd.github.io/GambonanzaAssets/ already hosts
a PNG for every sprite and texture in the game, and the manager loads its
previews straight from there. What that site's catalogue does NOT carry is the
one number the manager cannot do without: where a sprite sits inside its atlas.
Replacing a single gambit icon means pasting it into a 512x512 sheet at exactly
the right rectangle, and only the game's own asset files know that rectangle.

So this script re-reads the install and writes:

    registry/assets/catalog.json   every sprite and texture, WITH rects
    registry/assets/texts.json     every localised string, all 11 languages

Entry ids are generated by the same rule the site uses (slug of the name, with
-2/-3 suffixes for collisions, sprites before textures, files in a fixed
order), so <id>.png on the site resolves for every entry here. --check-live
verifies that by diffing against the deployed catalogue.

    python3 tools/build-asset-catalog.py
    python3 tools/build-asset-catalog.py --game "/path/to/Gambonanza" --check-live

Requires: UnityPy (pip install UnityPy). Pillow is NOT needed - no pixels are
decoded, only metadata is read.
"""

from __future__ import annotations

import argparse
import json
import math
import os
import re
import sys
import urllib.request
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
OUT_DIR = ROOT / "registry" / "assets"

# Same three files, in the same order, as the site's extractor. The order is
# part of the id algorithm: it decides who wins a slug collision.
ASSET_FILES = ["globalgamemanagers.assets", "resources.assets", "sharedassets0.assets"]
STEAM_APP_ID = "3509230"

LIVE_CATALOG_URL = "https://bentrd.github.io/GambonanzaAssets/assets/catalog.json"

# UnityPy hands back the raw enum on read. The manager shows this so people know
# why re-saving a DXT sheet can nudge colours on parts they never touched:
# replacing one icon re-compresses the whole page.
TEXTURE_FORMATS = {
    1: "Alpha8", 2: "ARGB4444", 3: "RGB24", 4: "RGBA32", 5: "ARGB32",
    7: "RGB565", 9: "R16", 10: "DXT1", 12: "DXT5", 13: "RGBA4444", 14: "BGRA32",
    17: "RHalf", 20: "RFloat", 22: "RGB9e5Float", 24: "BC6H", 25: "BC7",
    26: "BC4", 27: "BC5", 34: "RG16", 47: "RG32", 48: "RGB48", 49: "RGBA64",
}
COMPRESSED_FORMATS = {"DXT1", "DXT5", "BC4", "BC5", "BC6H", "BC7"}


def format_name(raw) -> str:
    text = str(raw).replace("TextureFormat.", "")
    try:
        return TEXTURE_FORMATS.get(int(text), f"format {text}")
    except ValueError:
        return text

# One TextAsset per language, each holding the same two-level JSON:
# section -> key -> string. Display order; a language added later lands at the end.
LANG_ORDER = ["en", "fr", "ge", "sp", "pt_br", "ru", "pl", "tr", "jp", "ko", "zh"]

# ---------------------------------------------------------------------------
# Everything below this line is copied verbatim from the site's tools/extract.py
# and MUST stay in step with it, or ids drift and every preview 404s.
# ---------------------------------------------------------------------------

SKIP_NAME_PATTERNS = [
    r"sdf",
    r"\batlas\b",
    r"font texture",
    r"^ldr_lll",
    r"^mm[a-z]*noise",
    r"^noise\d",
    r"areatex",
    r"searchtex",
    r"tcp2_",
    r"emojione",
    r"^sactx-",
    r"default-particlesystem",
]

CATEGORY_RULES: list[tuple[str, str]] = [
    ("Chess pieces",       r"pieces?blanches|pieces?noires|spr_chesspiece|_[bw]$|pawn|rook|knight|bishop|queen|king"),
    ("Gambit icons",       r"spr_gambits|gambit"),
    ("Board & tiles",      r"tile|square|board|checker"),
    ("Bosses",             r"^boss_|spr_boss|onikaru|maskaruga|geisha|finalboss|portal"),
    ("Ascension & medals", r"ascend|medal|trophy"),
    ("Minigames",          r"gachapon|pachinko|wheels|slot"),
    ("Title & branding",   r"title|logo|publisher|splash|bluku"),
    ("Effects",            r"godray|fog|fade|circle|glow|aura|shadow|spark|smoke|ray|dot|triangle|tentacle|arm|sweat|fist|lemnisate|distort|ripple|crt|gradient|voronoi"),
    ("Cursors & arrows",   r"cursor|arrow|selection|highlight"),
    ("Icons & UI",         r"spr_ui|icon|button|check|cross|lock|pan_|paste|thumbup|panel|window|bar|slider"),
    ("Controllers",        r"xbox|nintendo|switch|steamdeck|gampad|gamepad|glyph|controller|buttons pack"),
    ("Social",             r"discord|steam|twitch"),
]

PRETTY_SUBS = [(r"^spr[_ ]?", ""), (r"^tex[_ ]?", ""), (r"_", " ")]


def categorise(name: str) -> str:
    low = (name or "").lower()
    for label, pattern in CATEGORY_RULES:
        if re.search(pattern, low):
            return label
    return "Other"


def pretty(name: str) -> str:
    out = name or ""
    for pat, rep in PRETTY_SUBS:
        out = re.sub(pat, rep, out, flags=re.IGNORECASE)
    return re.sub(r"\s+", " ", out).strip() or name


def should_skip(name: str) -> bool:
    low = (name or "").lower()
    return any(re.search(p, low) for p in SKIP_NAME_PATTERNS)


def slug(s: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", (s or "").lower()).strip("-") or "asset"


# ---------------------------------------------------------------------------
# Locating the game
# ---------------------------------------------------------------------------

def find_data_dir(game_dir: Path) -> Path | None:
    for sub in (
        "Gambonanza.app/Contents/Resources/Data",
        "Gambonanza_Data",
        "Gambonanza/Gambonanza_Data",
    ):
        d = game_dir / sub
        if (d / "globalgamemanagers").exists():
            return d
    return None


def resolve_game(explicit: str | None) -> tuple[Path, Path]:
    candidates = []
    if explicit:
        candidates.append(Path(explicit).expanduser())
    if os.environ.get("GAMBONANZA_DIR"):
        candidates.append(Path(os.environ["GAMBONANZA_DIR"]).expanduser())
    home = Path.home()
    candidates += [
        home / "Library/Application Support/Steam/steamapps/common/Gambonanza",
        home / ".local/share/Steam/steamapps/common/Gambonanza",
        home / ".steam/steam/steamapps/common/Gambonanza",
        Path("C:/Program Files (x86)/Steam/steamapps/common/Gambonanza"),
        Path("C:/Program Files/Steam/steamapps/common/Gambonanza"),
    ]
    for c in candidates:
        if not c.exists():
            continue
        data = find_data_dir(c)
        if data:
            return c, data
        for probe in (c, c / "Contents/Resources/Data"):
            if (probe / "globalgamemanagers").exists():
                return probe.parent, probe
    sys.exit(
        "Could not find your Gambonanza install. Pass it explicitly:\n"
        "    python3 tools/build-asset-catalog.py --game \"/path/to/Gambonanza\""
    )


def steam_build_id(game_dir: Path) -> str:
    acf = game_dir.parent.parent / f"appmanifest_{STEAM_APP_ID}.acf"
    try:
        m = re.search(r'"buildid"\s*"(\d+)"', acf.read_text(errors="ignore"))
        return m.group(1) if m else "unknown"
    except OSError:
        return "unknown"


# ---------------------------------------------------------------------------
# Catalogue
# ---------------------------------------------------------------------------

def build_catalog(data_dir: Path, build: str) -> dict:
    import UnityPy

    entries: list[dict] = []
    seen_ids: set[str] = set()

    def unique_id(base: str) -> str:
        candidate = base
        n = 2
        while candidate in seen_ids:
            candidate = f"{base}-{n}"
            n += 1
        seen_ids.add(candidate)
        return candidate

    for file_key in ASSET_FILES:
        path = data_dir / file_key
        if not path.exists():
            continue
        print(f"reading {file_key} …")
        env = UnityPy.load(str(path))

        # path_id -> texture record, in env order (the id algorithm depends on it).
        textures: dict[int, dict] = {}
        for obj in env.objects:
            if obj.type.name != "Texture2D":
                continue
            try:
                d = obj.read()
            except Exception:
                continue
            name = d.m_Name or f"Texture_{obj.path_id}"
            w, h = int(d.m_Width), int(d.m_Height)
            if w <= 0 or h <= 0 or should_skip(name):
                continue
            fmt = format_name(getattr(d, "m_TextureFormat", "?"))
            textures[obj.path_id] = {
                "kind": "texture",
                "name": name,
                "label": pretty(name),
                "width": w,
                "height": h,
                "format": fmt,
                "compressed": fmt in COMPRESSED_FORMATS,
                "category": categorise(name),
                "spriteCount": 0,
            }

        sprites: list[dict] = []
        for obj in env.objects:
            if obj.type.name != "Sprite":
                continue
            try:
                d = obj.read()
                parent_id = d.m_RD.texture.path_id
                rect = d.m_RD.textureRect
            except Exception:
                continue
            parent = textures.get(parent_id)
            if parent is None:
                continue  # atlas lives in another file, or was skipped
            name = d.m_Name or f"Sprite_{obj.path_id}"
            # textureRect is a FLOAT rect, and for any sprite the packer trimmed it
            # is fractional: SPR_Chain sits at 381.076, 223.848 wide. Truncating
            # loses a column and puts the replacement one pixel out. Snap outwards
            # to whole pixels - the same rounding the extractor uses when it writes
            # the PNG, so the image on the site is exactly this many pixels.
            x0, y0 = math.floor(rect.x), math.floor(rect.y)
            x1 = min(parent["width"], math.ceil(rect.x + rect.width))
            y1 = min(parent["height"], math.ceil(rect.y + rect.height))
            w, h = x1 - x0, y1 - y0
            if w <= 0 or h <= 0 or x0 < 0 or y0 < 0:
                continue
            parent["spriteCount"] += 1
            cat = categorise(name)
            sprites.append({
                "kind": "sprite",
                "name": name,
                "label": pretty(name),
                "width": w,
                "height": h,
                "category": cat if cat != "Other" else parent["category"],
                "format": parent["format"],
                "compressed": parent["compressed"],
                "atlas": parent["name"],
                "atlasWidth": parent["width"],
                "atlasHeight": parent["height"],
                # The bit the site's catalogue doesn't carry. Unity rects are
                # bottom-left origin; the manager flips them when it composites
                # (top = atlasHeight - y - h).
                "rect": [x0, y0, w, h],
                "_parentId": parent_id,
            })

        # Sprites are numbered first, then textures - same as the site, so the
        # ids match and every <id>.png over there resolves.
        for s in sprites:
            s["id"] = unique_id(slug(s["name"]))
        for t in textures.values():
            t["id"] = unique_id(slug(t["name"]))

        for s in sprites:
            parent = textures.get(s.pop("_parentId"))
            s["atlasId"] = parent["id"] if parent else None
            entries.append(s)
        entries.extend(textures.values())

    entries.sort(key=lambda e: (e["category"], e["label"].lower()))

    counts: dict[str, int] = {}
    for e in entries:
        counts[e["category"]] = counts.get(e["category"], 0) + 1

    return {
        "build": build,
        "counts": {
            "total": len(entries),
            "sprites": sum(1 for e in entries if e["kind"] == "sprite"),
            "textures": sum(1 for e in entries if e["kind"] == "texture"),
        },
        "categories": [{"name": k, "count": v} for k, v in sorted(counts.items())],
        "entries": entries,
    }


# ---------------------------------------------------------------------------
# Texts
# ---------------------------------------------------------------------------

def build_texts(data_dir: Path, build: str) -> dict:
    import UnityPy

    tables: dict[str, dict] = {}
    env = UnityPy.load(str(data_dir / "resources.assets"))
    for obj in env.objects:
        if obj.type.name != "TextAsset":
            continue
        try:
            d = obj.read()
        except Exception:
            continue
        name = (d.m_Name or "")
        if not name.startswith("trad_"):
            continue
        code = name[len("trad_"):]
        try:
            tables[code] = json.loads(bytes(d.m_Script).decode("utf-8") if isinstance(d.m_Script, (bytes, bytearray)) else str(d.m_Script))
        except Exception as exc:
            print(f"  ! {name}: {exc}")

    if not tables:
        print("  ! no trad_* tables found - texts.json will be empty")
        return {"build": build, "languages": [], "counts": {"texts": 0, "languages": 0}, "sections": []}

    languages = [c for c in LANG_ORDER if c in tables] + sorted(c for c in tables if c not in LANG_ORDER)
    base = tables[languages[0]]

    sections = []
    total = 0
    for section_name, section in base.items():
        if not isinstance(section, dict):
            continue
        rows = []
        for key in section:
            values = []
            for code in languages:
                table = tables.get(code) or {}
                value = (table.get(section_name) or {}).get(key)
                values.append(value if isinstance(value, str) else "")
            rows.append({"key": key, "values": values})
            total += 1
        if rows:
            sections.append({"name": section_name, "entries": rows})

    return {
        "build": build,
        "languages": languages,
        "counts": {"texts": total, "languages": len(languages)},
        "sections": sections,
    }


# ---------------------------------------------------------------------------

def check_live(catalog: dict) -> None:
    """Diff our ids against the deployed site's, so a drift is loud, not silent."""
    print(f"\nchecking ids against {LIVE_CATALOG_URL} …")
    try:
        with urllib.request.urlopen(LIVE_CATALOG_URL, timeout=20) as fh:
            live = json.loads(fh.read().decode("utf-8"))
    except Exception as exc:
        print(f"  ! could not fetch the live catalogue ({exc}) - skipping the check")
        return

    live_ids = {e["id"] for e in live.get("entries", [])}
    ours = {e["id"] for e in catalog["entries"]}
    missing = sorted(ours - live_ids)
    print(f"  live build {live.get('build')} - {len(live_ids)} entries")
    print(f"  ours build {catalog['build']} - {len(ours)} entries")
    print(f"  {len(ours & live_ids)} ids resolve to a preview on the site")
    if missing:
        print(f"  {len(missing)} have no preview yet (the site is on an older game build):")
        for m in missing[:20]:
            print(f"    {m}")
        if len(missing) > 20:
            print(f"    … and {len(missing) - 20} more")


def main() -> None:
    ap = argparse.ArgumentParser(description="Build the asset catalogue for the mod manager.")
    ap.add_argument("--game", help="Path to the Gambonanza install folder")
    ap.add_argument("--check-live", action="store_true", help="Diff ids against the deployed site catalogue")
    ap.add_argument("--texts-only", action="store_true")
    args = ap.parse_args()

    try:
        import UnityPy  # noqa: F401
    except ImportError:
        sys.exit("This needs UnityPy:\n\n    python3 -m pip install UnityPy\n")

    game_dir, data_dir = resolve_game(args.game)
    build = steam_build_id(game_dir)
    print(f"Gambonanza : {game_dir}")
    print(f"Steam build: {build}\n")

    OUT_DIR.mkdir(parents=True, exist_ok=True)

    if not args.texts_only:
        catalog = build_catalog(data_dir, build)
        (OUT_DIR / "catalog.json").write_text(json.dumps(catalog, separators=(",", ":")))
        print(f"\nwrote {len(catalog['entries'])} entries "
              f"({catalog['counts']['sprites']} sprites, {catalog['counts']['textures']} textures) "
              f"-> {OUT_DIR / 'catalog.json'}")
        if args.check_live:
            check_live(catalog)

    print("\nreading localised texts …")
    texts = build_texts(data_dir, build)
    (OUT_DIR / "texts.json").write_text(json.dumps(texts, separators=(",", ":"), ensure_ascii=False))
    print(f"wrote {texts['counts']['texts']} strings in {texts['counts']['languages']} languages "
          f"-> {OUT_DIR / 'texts.json'}")


if __name__ == "__main__":
    main()
